-- One row per CRM opportunity, with pipeline attribution flags.
-- Stub: returns zero rows with the typed columns the metric library needs.
select
    cast(null as varchar) as opportunity_id,
    cast(null as date   ) as created_date,
    cast(null as varchar) as rep_id,
    cast(null as varchar) as account_id,
    cast(null as date   ) as close_date,
    cast(null as varchar) as channel,
    cast(null as boolean) as is_new,
    cast(null as varchar) as segment,
    cast(null as varchar) as product_name,
    cast(null as varchar) as stage,
    cast(null as varchar) as csm,
    cast(null as varchar) as opportunity_type,
    cast(null as varchar) as campaign_name,
    cast(null as boolean) as marketing_touched,
    cast(null as varchar) as deal_size_tier,
    cast(null as varchar) as source,
    cast(null as varchar) as competitor,
    cast(null as double ) as opportunity_value,
    cast(null as double ) as arr_value,
    cast(null as double ) as days_to_close,
    cast(null as double ) as total_arr,
    cast(null as double ) as closed_won_count,
    cast(null as double ) as paid_attributed_pipeline,
    cast(null as double ) as total_pipeline,
    cast(null as double ) as referral_attributed_pipeline,
    cast(null as double ) as closed_won,
    cast(null as double ) as total_qualified,
    cast(null as double ) as organic_attributed_pipeline,
    cast(null as double ) as won_competitive_deals,
    cast(null as double ) as total_competitive_deals,
    cast(null as date   ) as first_touch_date,
    cast(null as boolean) as is_closed,
    cast(null as boolean) as is_won,
    cast(null as boolean) as is_qualified
where false
