metrics:
  - name: product_return_rate
    label: Product Return %
    description: Percentage of sold units returned by customers
    type: derived
    type_params:
      expr: return_rate
      metrics:
        - name: return_rate
    config:
      meta:
        metricId: product_return_rate
        tier: kpi
        vertical: customer
        industry: retail
